import { nextJsConfig } from "@repo/eslint-config/next-js";

/** @type {import("eslint").Linter.Config[]} */
export default [
  // Generated by `msw init public/` — vendor file, not ours to lint (ADR 0016).
  { ignores: ["public/mockServiceWorker.js"] },
  ...nextJsConfig,
  {
    // Playwright E2E (ADR 0025) runs outside the turbo task graph (its own
    // `e2e-web` CI job), so `turbo/no-undeclared-env-vars` — which wants every
    // env var declared in turbo.json — does not apply. `process.env.CI` is the
    // standard CI-detection var Playwright reads to switch retries/reporters.
    files: ["playwright.config.ts", "playwright.smoke.config.ts", "e2e/**/*.ts"],
    rules: { "turbo/no-undeclared-env-vars": "off" },
  },
];
