import { nextJsConfig } from "@repo/eslint-config/next-js";

/** @type {import("eslint").Linter.Config[]} */
export default [
  // Generated by `msw init public/` — vendor file, not ours to lint (ADR 0016).
  { ignores: ["public/mockServiceWorker.js"] },
  ...nextJsConfig,
  {
    // Playwright E2E (ADR 0025) runs outside the turbo task graph (its own
    // `e2e-web` CI job), so `turbo/no-undeclared-env-vars` — which wants every
    // env var declared in turbo.json — does not apply. `process.env.CI` is the
    // standard CI-detection var Playwright reads to switch retries/reporters.
    //
    // `react-hooks/rules-of-hooks` is off for the same "not this world" reason:
    // a Playwright fixture is `async ({ deps }, use) => { await use(value) }`,
    // and the rule reads that `use(...)` call as React 19's `use` hook being
    // called outside a component. There is no React in this directory, so the
    // rule can only produce false positives — and renaming the callback to
    // dodge it would trade Playwright's documented fixture idiom for a lint
    // artifact.
    files: ["playwright.config.ts", "playwright.smoke.config.ts", "e2e/**/*.ts"],
    rules: { "turbo/no-undeclared-env-vars": "off", "react-hooks/rules-of-hooks": "off" },
  },
  {
    // React Three Fiber's JSX (<group position…>, <meshStandardMaterial…>) is
    // three.js scene-graph vocabulary, not DOM — eslint-plugin-react cannot
    // know it (the documented R3F lint caveat). Scoped to the 3D adapter dir.
    files: ["app/configurator/scene/**/*.tsx"],
    rules: { "react/no-unknown-property": "off" },
  },
  {
    // Dev-only Node harnesses (the ADR 0073 headless 3D capture script) run
    // outside the turbo task graph (`node scripts/verify/…`), so — like the
    // e2e block above — `turbo/no-undeclared-env-vars` does not apply. They are
    // Node scripts that also carry a browser context inside Playwright's
    // `page.evaluate`, so they need both global sets (`globals` isn't a direct
    // dep of this app, hence the explicit list).
    files: ["scripts/**/*.mjs"],
    languageOptions: {
      globals: {
        process: "readonly",
        console: "readonly",
        URL: "readonly",
        performance: "readonly",
        setTimeout: "readonly",
        document: "readonly",
        window: "readonly",
        requestAnimationFrame: "readonly",
      },
    },
    rules: { "turbo/no-undeclared-env-vars": "off" },
  },
];
