import type { ConfigContext, ExpoConfig } from "expo/config";

// Importing the typed env runs validation (throws on invalid vars).
import "@repo/config/env/mobile";

export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  name: "mobile",
  slug: "mobile",
  version: "1.0.0",
  scheme: "mobile",
  platforms: ["ios", "android"],
  // App icon (iOS + store + Expo Go). PLACEHOLDER — a neutral slate "S"
  // monogram generated by scripts/generate-placeholder-assets.mjs; replace with
  // real brand art (same 1024² dimensions) before shipping.
  icon: "./assets/icon.png",
  // Native app identifiers — required for any native/EAS build and matched by
  // the Maestro `appId` (.maestro/*.yml, ADR 0005). Reverse-domain of the org
  // (bepositive.cz); change here + in the Maestro flows if the org domain moves.
  ios: { bundleIdentifier: "cz.bepositive.mobile" },
  android: {
    package: "cz.bepositive.mobile",
    // Android adaptive icon: a transparent-background foreground composited over
    // `backgroundColor`. PLACEHOLDER (same generator). Keep the foreground art
    // inside the safe zone when replacing.
    adaptiveIcon: {
      foregroundImage: "./assets/adaptive-icon.png",
      backgroundColor: "#1e293b",
    },
  },
  // Follow the OS light/dark setting; drives NativeWind v5's `@variant dark`
  // (system default per ADR 0004). Without this, native locks to light.
  userInterfaceStyle: "automatic",
  web: {
    bundler: "metro",
    output: "server",
    favicon: "./assets/favicon.png",
  },
  // `expo-system-ui` must be a registered plugin (not just installed) — its
  // prebuild mod is what applies `userInterfaceStyle` to Android; without it the
  // property is ignored on Android (iOS is handled by Expo core).
  plugins: [
    "expo-router",
    "expo-system-ui",
    // Splash screen (expo-splash-screen plugin owns the native splash config in
    // SDK 52+; the top-level `splash` key is legacy). `image` is centered on
    // `backgroundColor`. PLACEHOLDER art (scripts/generate-placeholder-assets.mjs).
    [
      "expo-splash-screen",
      {
        image: "./assets/splash-icon.png",
        backgroundColor: "#1e293b",
        imageWidth: 200,
      },
    ],
  ],
});
